### PR TITLE
added deploy nopcommerce on azure app service

### PR DESCRIPTION
**Pull request by ninefyi**
Hi, I created issue #151. Please let me know if I have anything wrong.

### CODE REVIEW

**Comment by aaronamm** [comment]
@ninefyi  Thank you so your contribution.

However, I think it would be nice if you could separated this document in to two documents.
- 1st document, just use simple setup Azure SQL database, App Service, Storage and nopCommerce. I think it will simplify our document and it is easy for a beginner to follow.
- 2nd document, add more secured infra by using private network.

Thanks.

**Comment by ninefyi** [comment]
@aaronamm Sure, I will follow your comment.

**Comment by mildronize** [comment]
I think I should be better if you can add some brief explanation what happen in each step. I will be more easy for audience to catch up the content. @ninefyi

**Comment by ninefyi** [comment]
I already changed to create the simple way installation first. It is a better way to follow up for simple installation. Could you please review and let me know any feedback. @mildronize @aaronamm

**Review by aaronamm — CHANGES_REQUESTED** [review]
@ninefyi  I have checked out your PR and it look good.
The content focus on screenshot that we can later improve it by adding more description but we don't need to do in this PR.

However, since this is a small PR, could you please squash all commits and make this PR to have only commit.

Thanks.

FYI here is a screenshot from of this PR content when rending in a browser.

image

**Comment by ninefyi** [comment]
@aaronamm I already merge all commits into one commit. Could you please check again and let me know?

**Comment by aaronamm** [comment]
@ninefyi  Thanks for squash multiple commits.

**Review by aaronamm — APPROVED** [review]

**Pull request merged**
