### PR TITLE
Add react page

### PR DESCRIPTION
**Pull request by mildronize**
Please review my PR 😴

### CODE REVIEW

**Review by aaronamm — CHANGES_REQUESTED** [review]
You PR looks good. 
I have only one comment.

If it is a React App project, I think `create-react-app` to the best option to create a project.

Could you please add a section of how to React App and some short contents?
For example:
- How  to use create from a command line with TypeScript template
- How to run React project
- Show a list of the generated project structure with `tree command` , select only value folders and exclude npm_packages list.
e.g.
```
yarn create react-app my-app --template typescript
```

```
aaron@aaron-pc:~/projects$ tree my-app -I node_modules
my-app
├── README.md
├── package.json
├── public
│   ├── favicon.ico
│   ├── index.html
│   ├── logo192.png
│   ├── logo512.png
│   ├── manifest.json
│   └── robots.txt
├── src
│   ├── App.css
│   ├── App.test.tsx
│   ├── App.tsx
│   ├── index.css
│   ├── index.tsx
│   ├── logo.svg
│   ├── react-app-env.d.ts
│   ├── reportWebVitals.ts
│   └── setupTests.ts
├── tsconfig.json
└── yarn.lock

```

FYI https://zaiste.net/posts/tree-ignore-directories-patterns/


```
yarn start
```

**Comment by mildronize** [comment]
@aaronamm I understand 😁

**Comment by mildronize** [comment]
Done @aaronamm  thank you.

**Review by aaronamm — APPROVED** [review]
You did a good job.

**Pull request merged**
