### PR TITLE
Share my learned about React props

### PR DESCRIPTION
**Pull request by Pobx**
Please review my shared about react props.

### CODE REVIEW

**Review by mildronize — CHANGES_REQUESTED** [review]
Good PR. You do the nice work.

Here my suggestion, modify and recommit again.
- Here is look like basic tutorial, It should have a full code for 1 file in React JS. The beginner will be easy understanding.
- Each Block of content should have some description, how it work?
- Each code block you should use 

```
For heading of block code like this. ---> ```
It should replace like ---> ```jsx
for syntax highlighting
```

Last word: (Optional, you no need to add in this PR) 
- Here is good idea to make React 101 for Beginner. However, this article is lack of completeness. I think it can improve for easy to understand for beginner.

Thank you for your PR. To be a part of .NET Thailand.
Happy Hacktoberfest 2021

**Comment by aaronamm** [comment]
@Pobx Nice work, thanks for your contribution and thanks, @mildronize for coding review.
However, since this is a small PR, could you please squash all commits to 1 commit or git reset --soft.
I think 1 commit for this PR is okay.

Thanks.

**Comment by Pobx** [comment]
Thank you

**Review by mildronize — APPROVED** [review]

**Comment by mildronize** [comment]
@Pobx Merged. Thank you for your contribution.

**Pull request merged**
