### PR TITLE
Fix todo links in README.md

### PR DESCRIPTION
**Pull request by kaiwanyawit-chawankul**
- add link to Github Issues
- add link to Contribute on text "the following link"
- remove link to the same page (the last link)

Ticket: https://github.com/dotnetthailand/dotnetthailand.github.io/issues/99

### CODE REVIEW

**Comment by kidchenko** [comment]
The PR number #100! Yaaaay

cc @aaronamm

**Comment by aaronamm** [comment]
@kaiwanyawit-chawankul 
l something does not right, could you please rebase this PR. 
It should show only your commit and after that I will merge your PR.
image

**Comment by kidchenko** [comment]
cc @aaronamm this is a "optic illusion"

**Comment by kidchenko** [comment]
I mean, imo you can merge it, as I understand this PR was created direct in github you can see by the name of the branch.

image 

I believe if you do a rebase and merge (the last of the 3 options in the merge button)

**Comment by kaiwanyawit-chawankul** [comment]
@aaronamm Please check it again. I tried to revert a change by remove file and use Header.js from master

**Comment by aaronamm** [comment]
@kaiwanyawit-chawankul If I merge your PR, there will be some unintended commits to main branch as I have highlighted. 
It is possible that there is some force push commits in that main branch which has happened after you created this PR.

image

Would it be possible for you to work on this PR locally by rebase/reset to make your changes on top the latest commit in the main branch.

Here is my suggestion.

Let assume that you have two remotes:
- upstream => git@github.com:dotnetthailand/dotnetthailand.github.io.git
- origin => git@github.com:kaiwanyawit-chawankul/dotnetthailand.github.io.git

You can use the following commands to rebase your PR.
```sh
$ git checkout patch-1
$ git fetch upstream
$ git rebase upstrem/main
```
Then you will have log history like this in your computer.
```sh
22ddb0e (HEAD -> patch-1) Update Header.js
5487b64 Delete dotnetthailand-logo-dark-background.svg
f5d88c9 Fix todo links in README.md
5c533a6 feat: support dotnet thailand logo on dark background
005d008 (upstream/main, origin/main, origin/HEAD, main) Merge pull request #103 from mildronize/fix-fluent-icon-on-prod
2973a14 fix: initialize Icons of Fluent UI in gatsby (Load from locally)
```
Since your PR is a little small change and I think you accidentally deleted dotnetthailand-logo-dark-background.svg.
Please could you reset what your have changed and make only one commit for this PR (Only changes in REDME.md).
Here are commands that I suggest:
```sh
git reset --soft 005d00889ffdf2761089a24b4864216ab08c6f5c
git add .
git commit -m "Fix todo links in README.md"
```
Then you will have only one comit ahead the main branch.
Finally you can force push to your PR to have clean commit history.
``` sh
git push -uf origin patch-1
```

**Comment by kaiwanyawit-chawankul** [comment]
@aaronamm Thank you for your help and a clear instruction. I followed your steps and push a new commit `3d4e2a7` to this branch. Please check the PR again ^^

**Comment by aaronamm** [comment]
@kaiwanyawit-chawankul  Thank for your contribution. The commit is clean now.
Merged.

**Review by aaronamm — APPROVED** [review]

**Pull request merged**
