### PR TITLE
Hotfix Linkpath Overscreen in Safari

### PR DESCRIPTION
**Pull request by Him-2C**
**change log**
- fix, add word-wrap: break-word; for fix overscreen in Safari

### CODE REVIEW

**Comment by aaronamm** [comment]
@Him-2C  Could you please add screenshot of the result on a page that you fix on both Chrome and Safari mobile/desktop version?

Thanks.

**Comment by aaronamm** [comment]
@Him-2C Should we rename `word-wrap` to `overflow-wrap`?
REF https://stackoverflow.com/a/15137272/1872200

**Comment by Him-2C** [comment]
> @Him-2C Could you please add screenshot of the result on a page that you fix on both Chrome and Safari mobile/desktop version?
> 
> Thanks.

**Chrome**

localhost_8000_(iPhone 6_7_8)


**Firefox**

Screen Shot 2021-03-31 at 20 39 39


**Safari**

Screen Shot 2564-03-31 at 20 37 51

**Comment by aaronamm** [comment]
I think we should go for the standard, most major browser now support `overflow-wrap`, please rename it to `overflow-wrap: break-word;`
After that I will merge your PR. Thanks.

REF https://caniuse.com/?search=Overflow-wrap

**Comment by aaronamm** [comment]
@Him-2C Thanks for your hard working. I appreciate it.
BTW, I suggest you to change your username to Him-2p-2c. It would be fun.

**Pull request merged**
