### PR TITLE
Docker file info

### PR DESCRIPTION
**Pull request by utarn**

### CODE REVIEW

**Comment by mildronize** [comment]
@utarn I think you should add some reference or read more articles. the reader can getting understand easier. Thank you very much.

**Comment by utarn** [comment]
actually, these are from the book I have written. https://www.scribd.com/document/478584064/%E0%B8%95%E0%B8%B3%E0%B8%A3%E0%B8%B2%E0%B8%81%E0%B8%B2%E0%B8%A3%E0%B8%9B%E0%B8%A3%E0%B8%B0%E0%B8%A1%E0%B8%A7%E0%B8%A5%E0%B8%9C%E0%B8%A5%E0%B8%81%E0%B8%A5%E0%B8%B8-%E0%B8%A1%E0%B9%80%E0%B8%A1%E0%B8%86-Cloud-Computing. Should I include my book link as a reference?

**Comment by mildronize** [comment]
@utarn Yes, please ref to your books, it'll good for reader.
Thank you very much.

**Comment by utarn** [comment]
sorry for the late fix.

**Review by ponggun — APPROVED** [review]
There is already a document referenced.

**Pull request merged**
