### PR TITLE
fix facebook comment doesnt dark theme when using dark mode

### LINKED ISSUE #122: Facebook Comment doesn't dark theme
# Problem
- Unreadable text on dark theme

image

### PR DESCRIPTION
**Pull request by iamgique**

### CODE REVIEW

**Comment by mildronize** [comment]
@iamgique Thank you for your PR. Very nice,

Firstly, I don't see any change in `package.json`, so the `yarn.lock` should not be changed. 
Could you remove that file from this PR.

Thank you very much.

**Comment by iamgique** [comment]
I'm so sorry for yarn.lock. Currently, I checkout origin/main yarn.lock and commit already
I just only change file 'FacebookComment.tsx'

**Comment by mildronize** [comment]
@aaronamm I don't sure for Facebook comment feature, it should be work on local? (I mean your codebase, not this PR)

**Comment by iamgique** [comment]
@mildronize You can try by real url 

replace `data-href={url}` to `data-href=https://facebook.com/something` krub

**Comment by aaronamm** [comment]
@mildronize The Facebook comment shows on a local machine but does not point to the right domain which is okay because we resolve a correct domain at build time.

@iamgique This PR looks good to me. However, since this is a small PR, could you please squash all commits to one commit and then force push to your branch.

After you have made this PR to have only one commit, I will merge your PR.
Thanks.

**Comment by aaronamm** [comment]
@mildronize  This PR does not change any business logic, I think it is okay.

**Comment by mildronize** [comment]
@iamgique Here is my local result

image

```diff
 const commentPlaceHolderStyle = showElement => css`
    margin-top: 10px;
    width: 100%;
    background: rgba(254, 254, 254, 0.9);
    border: 1px solid #fefefe;
    padding: 10px;
-   border-radius: 20px;
+   border-radius: 5px;
    display: ${showElement ? 'block' : 'none'};
`;
```

Could you please change the `border-radius` to `5px`? i will better.
Thank you very much @iamgique .

**Comment by iamgique** [comment]
@mildronize I decided choose radius 20px because I chosen it.
If you wanna use 5 please tell me why krub?

248337708_612467049795047_5719327053805731807_n

**Comment by iamgique** [comment]
@aaronamm I've done krub

**Comment by mildronize** [comment]
@iamgique Sorry, I forget to tell the reason, if the `border-radius` is 20, the design is the consistency with the current theme.

**Review by mildronize — APPROVED** [review]
Good PR. Solved the problem.

Happy Hacktoberfest 2021

**Pull request merged**
